name: jiant
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - numpy
  - scikit-learn
  - pandas

  - bokeh
  - ipykernel
  - pytz
  - jsondiff
  - pip
  - pip:
      - ipdb
      - tensorboard
      - tensorboardX
      - sendgrid
      - pyhocon
      - nose2
      - pre-commit
      - python-Levenshtein
      - google-cloud-logging
      - spacy
      - nltk
      - sacremoses
      # Hugging Face Transformers (replaces pytorch_pretrained_bert and pytorch_transformers)
      - transformers