name: jiant
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13.1
  - torchvision
  - numpy
  - scikit-learn
  - pandas

  - bokeh
  - ipykernel
  - pytz=2022.2.1
  - jsondiff
  - pip
  - pip:
      - allennlp 
      - ipdb
      - tensorboard
      - tensorboardX
      - sendgrid
      - pyhocon
      - nose2
      - pre-commit
      - python-Levenshtein
      - google-cloud-logging
      - spacy
      - nltk
      - sacremoses
      # Hugging Face Transformers (replaces pytorch_pretrained_bert and pytorch_transformers)
      - transformers