name: jiant
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13.1
  - torchvision
  - numpy=1.23.0
  - scikit-learn=1.1.0
  - pandas=1.5.0
  # Updated version of Bokeh
  - bokeh=2.4.2
  - ipykernel=6.12.0
  - pytz=2022.2.1
  - jsondiff
  - pip
  - pip:
      - allennlp==2.10.0  # Update AllenNLP to a newer version
      - ipdb
      - tensorboard
      - tensorboardX==2.6
      - sendgrid==6.0.0  # Update SendGrid
      - pyhocon==0.3.56
      - nose2
      - pre-commit==2.20.0  # Latest pre-commit version
      - python-Levenshtein==0.12.2
      - google-cloud-logging==3.0.2
      - spacy==3.3.0
      - nltk==3.7
      - sacremoses
      # Hugging Face Transformers (replaces pytorch_pretrained_bert and pytorch_transformers)
      - transformers==4.25.0  # Latest stable version
